
services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: paymint-api-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
